services:
  platform-service:
    image: platform-service
    build:
      context: ..
      dockerfile: src/PlatformService/Dockerfile
    ports:
      - 5000:58295
    environment:
      ASPNETCORE_HTTP_PORTS: 5000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432