GET {{HostAddress}}/api/platforms/08db7272-6ae3-bbc5-0015-5dd9eab40000
Accept-Language: {{Lang}}

###
GET {{HostAddress}}/api/platforms
Accept-Language: {{Lang}}

###

POST {{HostAddress}}/api/platforms
Content-Type: application/json
Accept-Language: {{Lang}}

{
  "Name": "Ubuntu",
  "Publisher": "GNU/Linux",
  "Cost": "Free"
}

###

DELETE {{HostAddress}}/api/platforms/1
Accept-Language: {{Lang}}


###