GET {{HostAddress}}/api/platforms/08db7272-6ae3-bbc5-0015-5dd9eab40000

###
GET {{HostAddress}}/api/platforms

###

POST {{HostAddress}}/api/platforms
Content-Type: application/json

{
  "Name": "Ubuntu",
  "Publisher": "GNU/Linux",
  "Cost": "Free"
}

###

DELETE {{HostAddress}}/api/platforms/08db7272-6ae3-bbc5-0015-5dd9eab40000


###