GET {{BaseUrl}}/platforms/10
Accept-Language: {{Lang}}

###
GET {{BaseUrl}}/platforms
Accept-Language: {{Lang}}

###

POST {{BaseUrl}}/platforms
Content-Type: application/json
Accept-Language: {{Lang}}

{
  "Name": "Ubuntu",
  "Publisher": "GNU/Linux",
  "Cost": "Free"
}

###

DELETE {{BaseUrl}}/platforms/1
Accept-Language: {{Lang}}


###