<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Core.Api" />
        <PackageReference Include="Grpc.Net.Common" />
        <PackageReference Include="Grpc.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\*.proto">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Protobuf>
    </ItemGroup>

    <ItemGroup>
        <PackageVersion Update="Grpc.Core.Api" Version="2.54.0" />
    </ItemGroup>

</Project>
